### ISSUE TITLE
OPR Doesn't work on events before 2010

### ISSUE THREAD

**Issue by wjorda** [Thing342/pyTBA#4]
`match_matrix()` appears to return an empty array.
```
Traceback (most recent call last):
  File "/home/wes/JetBrains/apps/PyCharm-P/ch-0/171.2822.19/helpers/pydev/pydevd.py", line 1624, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/wes/JetBrains/apps/PyCharm-P/ch-0/171.2822.19/helpers/pydev/pydevd.py", line 1001, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/wes/JetBrains/apps/PyCharm-P/ch-0/171.2822.19/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/wes/PycharmProjects/TBAImport/import_events.py", line 244, in <module>
    proc_event(year, event_code)
  File "/home/wes/PycharmProjects/TBAImport/import_events.py", line 234, in proc_event
    proc_records(year, code, event_path + 'alliances.csv', event_path + 'rankings.csv', proc_oprs=True)
  File "/home/wes/PycharmProjects/TBAImport/import_events.py", line 136, in proc_records
    oprs = stats.opr(e, dpr="/alliances/##OPPALLIANCE/score")
  File "/home/wes/PycharmProjects/pyTBA/pytba/stats.py", line 115, in opr
    assert len(opr) == len(event.teams)
AssertionError
Error evaluating: thread_id: pid_11138_id_140447940598248
frame_id: 43964504
scope: FRAME
attrs: opr
Traceback (most recent call last):
  File "/home/wes/JetBrains/apps/PyCharm-P/ch-0/171.2822.19/helpers/pydev/_pydevd_bundle/pydevd_vars.py", line 250, in resolve_compound_variable
    return resolver.get_dictionary(var)
  File "/home/wes/JetBrains/apps/PyCharm-P/ch-0/171.2822.19/helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 463, in get_dictionary
    ret['min'] = obj.min()
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
Error evaluating: thread_id: pid_11138_id_140447940598248
frame_id: 43964504
scope: FRAME
attrs: matrix
Traceback (most recent call last):
  File "/home/wes/JetBrains/apps/PyCharm-P/ch-0/171.2822.19/helpers/pydev/_pydevd_bundle/pydevd_vars.py", line 250, in resolve_compound_variable
    return resolver.get_dictionary(var)
  File "/home/wes/JetBrains/apps/PyCharm-P/ch-0/171.2822.19/helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 463, in get_dictionary
    ret['min'] = obj.min()
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
Error evaluating: thread_id: pid_11138_id_140447940598248
frame_id: 43964504
scope: FRAME
attrs: mat
Traceback (most recent call last):
  File "/home/wes/JetBrains/apps/PyCharm-P/ch-0/171.2822.19/helpers/pydev/_pydevd_bundle/pydevd_vars.py", line 250, in resolve_compound_variable
    return resolver.get_dictionary(var)
  File "/home/wes/JetBrains/apps/PyCharm-P/ch-0/171.2822.19/helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 463, in get_dictionary
    ret['min'] = obj.min()
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by wjorda** [comment]
Fixed in recent commit.
